### ISSUE TITLE
Problem publishing to Sonatype

### ISSUE THREAD

**Issue by nickelsberry** [47deg/LambdaTest#14]
From @nestorpersist 

"I am trying to push out a new version of LambdaTest to sonatype (using sbt publishSigned) and am getting the following errors.

Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/fortysevendeg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.jar.asc was refused by the server: Forbidden

(docs/*:publishSignedConfiguration) Repository for publishing is not specified."

Can you take a look at this?

**Comment by nestorpersist** [comment]
Nothing on my side is changed in the publication part.

PUBLISH_USERNAME=47deg.developer
PUBLISH_PASSWORD= starts with Nk

I am able to log directly into sonatype with these.

I do have the gpg file on my machine.

Here is my pub key. There is also a secring.gpg file in the same dir.
These are the same files that worked for previous versions.

The FORBIDDEN error states that credentials are ok but I don’t have access to the specific repo.

https://support.sonatype.com/hc/en-us/articles/213464668-Troubleshooting-Artifact-Deployment-Failures <https://support.sonatype.com/hc/en-us/articles/213464668-Troubleshooting-Artifact-Deployment-Failures>

**Comment by fedefernandez** [comment]
I'm wondering if we have lost the permissions for publishing under com.fortydevendeg package. 

I'll try to check that tomorrow. On the other hand, maybe it's time to migrate to com.47deg, what do you think?

**Comment by nestorpersist** [comment]
I changed to com.47deg and am getting the same error!

[error] (lambdatest/*:publishSigned) java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.jar.asc was refused by the server: Forbidden
[error] (docs/*:publishSignedConfiguration) Repository for publishing is not specified.

**Comment by fedefernandez** [comment]
Hi @nestorpersist, I found the problem, the last version was published on Jan 02, 2017. From that date, there were two changes on the build.sbt:
* https://github.com/47deg/LambdaTest/commit/cc4049bd2cc0725d3cbec4ef814311c5c0efc79e#diff-fdc3abdfd754eeb24090dbd90aeec2ce
* https://github.com/47deg/LambdaTest/commit/c629850d7a15f3e2caa757870b0410edf38940f1#diff-fdc3abdfd754eeb24090dbd90aeec2ce

After some research, I found the problem is that a new module was added (docs) leaving the main code in the root module. That creates incompatibilities, like avoiding the publication from the root module. I've created a new pull request that creates the root module, moving all previous code to a new one under the `lambdatest` folder. This allows the publication of the artifact from the root project.

Please, bear in mind that the project compiles but there are multiple tests that fail, potentially due to a bad migration of the settings.

https://github.com/47deg/LambdaTest/pull/15

Ideally, the project should be migrated to SBT 1.x with a configuration based on an AutoPlugin.

Hope this helps.

**Comment by nestorpersist** [comment]
Thanks for the pull request fixing the module structure. I have merged it and fixed up a few loose ends.

But it still is not working. 

Doing a publishSigned from lambda-test project results in

[error] (lambda-test/*:publishSigned) java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.jar.asc was refused by the server: Forbidden

P.S. Note that many test are designed to fail. They demo how to find errors using this testing framework.

**Comment by fedefernandez** [comment]
Are we still getting the error:
`[error] (docs/*:publishSignedConfiguration) Repository for publishing is not specified.`

**Comment by nestorpersist** [comment]
No. Reorg of modules did seem to fix that.

**Comment by juanpedromoreno** [comment]
Hi @nestorpersist, I'm afraid that without having `pgp` files, neither the `pgp passphrase`, debugging this issue on our side it's hard.

Could you double check that `GPG_PASSPHRASE` is correctly provided in scope as an environment variable or system property?

**Comment by nestorpersist** [comment]
I did a test where I changed the env var for the gpg password.
I now get a bad password error from publishSigned.  This verifies that 
the gpg password env var was correct.

From Sonatype docs:

Code 403 - Forbidden

The login credentials sent were valid, but the user does not have permission to upload to the repository.  Go to "administration/security" in the Nexus UI, and bring up the user (or the user's role if they are mapped via an external role mapping) and examine the role tree to see what repository privileges they have been assigned.  A user will need create and update privileges for a repository to be able to deploy into it.

**Comment by juanpedromoreno** [comment]
I went through this issue with the provided information (gpg files and passpharase) and everything was fine. I was able to `publishSigned` LambdaTest *1.3.1* successfully:

```bash
[info] Done packaging.
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.jar.asc
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1-javadoc.jar.asc
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.pom
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1-javadoc.jar
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1-sources.jar.asc
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.pom.asc
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1-sources.jar
[info] 	published lambda-test_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/47deg/lambda-test_2.12/1.3.1/lambda-test_2.12-1.3.1.jar
```

Afterwards, I released and closed accordingly from the Sonatype UI.
